import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  en: {
    // Navbar
    lobby: 'Lobby',
    tournaments: 'Tournaments',
    profile: 'Profile',
    login: 'Login',
    logout: 'Logout',
    online: 'Online',
    offline: 'Offline',
    
    // Lobby
    chooseYourBattle: 'Choose Your Battle',
    selectGameMode: 'Select a game mode and jump into the action',
    playNow: 'Play Now',
    selectMode: 'Select a Mode',
    leaderOnly: 'Leader Only',
    onlyLeaderCanStart: 'Only the group leader can start a match',
    notEnoughPlayers: 'You need {min} player(s) in your group for this mode',
    tooManyPlayers: 'Maximum {max} player(s) allowed for this mode',
    pressToFind: 'Press to find a match in',
    playersOnline: 'Online',
    activeMatches: 'Active Matches',
    totalAccounts: 'Accounts',
    totalMatches: 'Matches Played',
    totalSquads: 'Squads',
    avgMatchesPerDay: 'Avg/Day',
    currentGame: 'Current Game',
    serverStatus: 'Server Status',
    optimal: 'Optimal',
    
    // Game modes
    ranked: 'Ranked',
    rankedDesc: 'Competitive matches with skill-based ranking system',
    casual: 'Casual',
    casualDesc: 'Relaxed matches for fun without rank pressure',
    tournament: 'Tournament',
    tournamentDesc: 'Official tournament matches and qualifiers',
    custom: 'Custom',
    customDesc: 'Create your own match with custom rules',
    playersOnlineCount: 'players online',
    playerOnline: 'player online',
    searching: 'searching',
    rules: 'Rules',
    rulesTitle: 'Game Rules',
    understood: 'Understood',
    
    // Match Search
    searchingMatch: 'Searching for a match...',
    matchFound: 'Match Found',
    matchInProgress: 'Match In Progress',
    matchFunctionalityComingSoon: 'Match functionality coming soon',
    minimize: 'Minimize',
    startingIn: 'Starting in',
    connecting: 'Connecting...',
    connectingToServer: 'Connecting to server...',
    scanning: 'Scanning',
    joining: 'Joining...',
    joiningMatch: 'Joining match...',
    searchingDesc: 'Looking for players near your skill level',
    matchFoundDesc: 'Preparing your lobby',
    connectingDesc: 'Joining the match server',
    searchTime: 'Search Time',
    elapsed: 'Elapsed',
    playersFound: 'Players Found',
    playersInQueue: 'Players in Queue',
    lobbySlots: 'Lobby Slots',
    cancelSearch: 'Cancel Search',
    doNotClose: 'Please do not close this window',
    errorJoiningQueue: 'Error joining queue',
    leaderCancelledSearch: 'The leader cancelled the search',
    errorOccurred: 'An error occurred',
    team: 'Team',
    close: 'Close',
    
    // Iris Required
    irisRequired: 'Iris Anti-Cheat Required',
    irisRequiredDesc: 'You need to have Iris running to search for a match',
    irisStep1Title: 'Download Iris',
    irisStep1Desc: 'Go to the Anti-Cheat page and download Iris',
    irisStep2Title: 'Install & Launch',
    irisStep2Desc: 'Install the application and log in with Discord',
    irisStep3Title: 'Keep it running',
    irisStep3Desc: 'Iris must stay open while you play',
    irisInfoText: 'Iris protects fair play by verifying your PC integrity. It runs in the background with minimal impact.',
    downloadIris: 'Download Iris',
    close: 'Close',
    
    // Party Panel
    squad: 'Squad',
    party: 'Party',
    pendingInvites: 'Pending Invites',
    groupOf: '\'s group',
    members: 'members',
    accept: 'Accept',
    decline: 'Decline',
    leader: 'Leader',
    you: 'You',
    lvl: 'LVL',
    irisConnected: 'Iris Connected',
    irisDisconnected: 'Iris Disconnected',
    makeLeader: 'Make Leader',
    kickFromParty: 'Kick from Party',
    invitePlayer: 'Invite Player',
    emptySlot: 'Empty Slot',
    inviteFriends: 'Invite Friends',
    leaveParty: 'Leave Party',
    transferToLeave: 'Transfer leadership to leave the party',
    partyPrivacy: 'Party Privacy',
    inviteOnly: 'Invite Only',
    
    // Ranked rules
    rankedRule1: 'Matches are played in Best of 5 format',
    rankedRule2: 'All players must have their microphone enabled',
    rankedRule3: 'Cheating or exploiting will result in a permanent ban',
    rankedRule4: 'Respect your opponents and teammates at all times',
    
    // Casual rules
    casualRule1: 'Play for fun, no pressure',
    casualRule2: 'Friendly behavior is expected',
    casualRule3: 'Leaving early is allowed but not encouraged',
    
    // Tournament rules
    tournamentRule1: 'Check-in 15 minutes before your match',
    tournamentRule2: 'All official competitive rules apply',
    tournamentRule3: 'Match results are final',
    tournamentRule4: 'Prizes will be distributed within 48 hours',
    
    // Custom rules
    customRule1: 'The host defines the rules',
    customRule2: 'Make sure all players agree to the rules',
    customRule3: 'Have fun!',
    
    // Tournaments page
    tournamentsTitle: 'Tournaments',
    tournamentsSubtitle: 'Compete in organized competitive events',
    tournamentComingSoon: 'Tournament system is under development. Soon you\'ll be able to participate in organized competitive events.',
    tournamentSystemTitle: 'Tournament System',
    upcoming: 'Upcoming',
    ongoing: 'Ongoing',
    completed: 'Completed',
    date: 'Date',
    prize: 'Prize',
    players: 'Players',
    comingSoon: 'Coming Soon',
    backToLobby: 'Back to Lobby',
    
    // Profile page
    profileTitle: 'Profile',
    profileSubtitle: 'View your stats, achievements, and settings',
    profileComingSoon: 'Profile Coming Soon',
    profileComingSoonDesc: 'Your profile page with stats, match history, and customization options will be available soon.',
    matches: 'Matches',
    winRate: 'Win Rate',
    rank: 'Rank',
    loading: 'Loading...',
    level: 'Level',
    total: 'total',
    nextLevel: 'Next level',
    victories: 'Victories',
    defeats: 'Defeats',
    coins: 'Coins',
    editProfile: 'Edit Profile',
    save: 'Save',
    saving: 'Saving...',
    cancel: 'Cancel',
    username: 'Username',
    avatarUrl: 'Avatar URL',
    platform: 'Platform',
    searchPlayer: 'Search player...',
    playerNotFound: 'Player not found',
    backToLobby: 'Back to lobby',
    wins: 'Wins',
    losses: 'Losses',
    winrate: 'Winrate',
    resetStats: 'Reset Stats',
    resetStatsTitle: 'Reset your stats?',
    resetStatsDesc: 'This will reset your wins, losses and points to 0. Your XP and level will be kept.',
    confirmReset: 'Reset',
    resetting: 'Resetting...',
    deleteAccount: 'Delete Account',
    deleteAccountTitle: 'Delete your account?',
    deleteAccountDesc: 'This action is permanent and cannot be undone. All your data will be lost.',
    typeDeleteConfirm: 'Type DELETE to confirm',
    confirmDelete: 'Delete',
    deleting: 'Deleting...',
    
    // Login dialog
    loginTitle: 'Login to NoMercy',
    loginSubtitle: 'Connect with Discord to access all features',
    continueWithDiscord: 'Continue with Discord',
    termsNotice: 'By logging in, you agree to our Terms of Service',
    
    // Admin
    admin: 'Admin',
    adminPanel: 'Admin Panel',
    adminPanelDesc: 'Manage game modes, rules, and players',
    gameModes: 'Game Modes',
    playerManagement: 'Players',
    searchPlayerPlaceholder: 'Search by username or Activision ID...',
    statsUpdated: 'Stats updated successfully!',
    saveStats: 'Save Stats',
    general: 'General',
    editRules: 'Rules',
    modeEnabled: 'Mode is enabled and visible to players',
    modeDisabled: 'Mode is disabled and hidden from players',
    noRulesYet: 'No rules defined yet',
    addNewRule: 'Add new rule',
    addRule: 'Add Rule',
    done: 'Done',
    saved: 'Changes saved!',
    adminTip: 'Changes are saved automatically. Toggle switches to enable/disable modes, and expand to edit rules.',
    queues: 'Queues',
    matchmakingQueues: 'Matchmaking Queues',
    playersCurrentlyInQueue: 'Players currently in queue',
    clearAllQueues: 'Clear All Queues',
    confirmClearQueues: 'Are you sure you want to remove all players from queues?',
    queuesCleared: 'Queues cleared',
    queueInfoTip: 'Clearing queues will remove all players currently searching for a match. They will need to search again.',
    addGameMode: 'Add Game Mode',
    newGameMode: 'New Game Mode',
    editModeName: 'Edit mode name',
    icon: 'Icon',
    modeType: 'Mode Type',
    addMode: 'Add Mode',
    deleteMode: 'Delete Mode',
    rulesDescription: 'Write rules for this mode (one rule per line)',
    cancel: 'Cancel',
    vipAccess: 'Grant VIP access to this player',
  },
  fr: {
    // Navbar
    lobby: 'Lobby',
    tournaments: 'Tournois',
    profile: 'Profil',
    login: 'Connexion',
    logout: 'Déconnexion',
    online: 'En ligne',
    offline: 'Hors ligne',
    
    // Lobby
    chooseYourBattle: 'Choisis ton Combat',
    selectGameMode: 'Sélectionne un mode de jeu et entre dans l\'action',
    playNow: 'Jouer',
    selectMode: 'Choisir un Mode',
    leaderOnly: 'Leader seulement',
    onlyLeaderCanStart: 'Seul le leader du groupe peut lancer un match',
    notEnoughPlayers: 'Il faut {min} joueur(s) dans le groupe pour ce mode',
    tooManyPlayers: 'Maximum {max} joueur(s) autorisé(s) pour ce mode',
    pressToFind: 'Appuie pour trouver un match en',
    playersOnline: 'En ligne',
    activeMatches: 'Matchs en cours',
    totalAccounts: 'Comptes',
    totalMatches: 'Matchs joués',
    totalSquads: 'Squads',
    avgMatchesPerDay: 'Moy/Jour',
    currentGame: 'Jeu en cours',
    serverStatus: 'État du serveur',
    optimal: 'Optimal',
    
    // Game modes
    ranked: 'Classé',
    rankedDesc: 'Matchs compétitifs avec système de classement',
    casual: 'Casual',
    casualDesc: 'Matchs détendus pour le plaisir sans pression',
    tournament: 'Tournoi',
    tournamentDesc: 'Matchs de tournois officiels et qualifications',
    custom: 'Personnalisé',
    customDesc: 'Crée ton propre match avec des règles personnalisées',
    playersOnlineCount: 'joueurs en ligne',
    playerOnline: 'joueur en ligne',
    searching: 'en recherche',
    rules: 'Règles',
    rulesTitle: 'Règles du jeu',
    understood: 'Compris',
    
    // Match Search
    searchingMatch: 'Recherche de match...',
    matchFound: 'Match Trouvé',
    matchInProgress: 'Match En Cours',
    matchFunctionalityComingSoon: 'Fonctionnalités du match bientôt disponibles',
    minimize: 'Réduire',
    startingIn: 'Début dans',
    connecting: 'Connexion...',
    connectingToServer: 'Connexion au serveur...',
    scanning: 'Analyse',
    joining: 'Rejoindre...',
    joiningMatch: 'Rejoindre le match...',
    searchingDesc: 'Recherche de joueurs de votre niveau',
    matchFoundDesc: 'Préparation du lobby',
    connectingDesc: 'Connexion au serveur de match',
    searchTime: 'Temps de recherche',
    elapsed: 'Écoulé',
    playersFound: 'Joueurs trouvés',
    playersInQueue: 'Joueurs en file',
    lobbySlots: 'Places du lobby',
    cancelSearch: 'Annuler la recherche',
    doNotClose: 'Veuillez ne pas fermer cette fenêtre',
    errorJoiningQueue: 'Erreur lors de la connexion à la file',
    leaderCancelledSearch: 'Le leader a annulé la recherche',
    errorOccurred: 'Une erreur est survenue',
    team: 'Équipe',
    
    // Iris Required
    irisRequired: 'Iris Anti-Cheat Requis',
    irisRequiredDesc: 'Vous devez avoir Iris en cours d\'exécution pour rechercher un match',
    irisStep1Title: 'Télécharger Iris',
    irisStep1Desc: 'Allez sur la page Anti-Cheat et téléchargez Iris',
    irisStep2Title: 'Installer et Lancer',
    irisStep2Desc: 'Installez l\'application et connectez-vous avec Discord',
    irisStep3Title: 'Gardez-le ouvert',
    irisStep3Desc: 'Iris doit rester ouvert pendant que vous jouez',
    irisInfoText: 'Iris protège le fair-play en vérifiant l\'intégrité de votre PC. Il fonctionne en arrière-plan avec un impact minimal.',
    downloadIris: 'Télécharger Iris',
    close: 'Fermer',
    
    // Party Panel
    squad: 'Escouade',
    party: 'Groupe',
    pendingInvites: 'Invitations en attente',
    groupOf: ' du groupe de',
    members: 'membres',
    accept: 'Accepter',
    decline: 'Refuser',
    leader: 'Leader',
    you: 'Vous',
    lvl: 'NIV',
    irisConnected: 'Iris Connecté',
    irisDisconnected: 'Iris Déconnecté',
    makeLeader: 'Nommer Leader',
    kickFromParty: 'Expulser du groupe',
    invitePlayer: 'Inviter un joueur',
    emptySlot: 'Place libre',
    inviteFriends: 'Inviter des amis',
    leaveParty: 'Quitter le groupe',
    transferToLeave: 'Transférez le leadership pour quitter',
    partyPrivacy: 'Confidentialité',
    inviteOnly: 'Sur invitation',
    
    // Ranked rules
    rankedRule1: 'Les matchs se jouent en Best of 5',
    rankedRule2: 'Tous les joueurs doivent avoir leur micro activé',
    rankedRule3: 'La triche ou l\'exploitation de bugs entraînera un ban permanent',
    rankedRule4: 'Respectez vos adversaires et coéquipiers en tout temps',
    
    // Casual rules
    casualRule1: 'Jouez pour le plaisir, sans pression',
    casualRule2: 'Un comportement amical est attendu',
    casualRule3: 'Partir tôt est autorisé mais pas encouragé',
    
    // Tournament rules
    tournamentRule1: 'Check-in 15 minutes avant votre match',
    tournamentRule2: 'Toutes les règles compétitives officielles s\'appliquent',
    tournamentRule3: 'Les résultats des matchs sont définitifs',
    tournamentRule4: 'Les prix seront distribués sous 48 heures',
    
    // Custom rules
    customRule1: 'L\'hôte définit les règles',
    customRule2: 'Assurez-vous que tous les joueurs acceptent les règles',
    customRule3: 'Amusez-vous !',
    
    // Tournaments page
    tournamentsTitle: 'Tournois',
    tournamentsSubtitle: 'Participez à des événements compétitifs organisés',
    tournamentComingSoon: 'Le système de tournois est en développement. Bientôt vous pourrez participer à des événements compétitifs organisés.',
    tournamentSystemTitle: 'Système de Tournois',
    upcoming: 'À venir',
    ongoing: 'En cours',
    completed: 'Terminé',
    date: 'Date',
    prize: 'Prix',
    players: 'Joueurs',
    comingSoon: 'Bientôt Disponible',
    backToLobby: 'Retour au Lobby',
    
    // Profile page
    profileTitle: 'Profil',
    profileSubtitle: 'Consulte tes stats, succès et paramètres',
    profileComingSoon: 'Profil Bientôt Disponible',
    profileComingSoonDesc: 'Ta page de profil avec stats, historique et personnalisation sera bientôt disponible.',
    matches: 'Matchs',
    winRate: 'Winrate',
    rank: 'Rang',
    loading: 'Chargement...',
    level: 'Niveau',
    total: 'total',
    nextLevel: 'Prochain niveau',
    victories: 'Victoires',
    defeats: 'Défaites',
    coins: 'Pièces',
    editProfile: 'Modifier le profil',
    save: 'Enregistrer',
    saving: 'Enregistrement...',
    cancel: 'Annuler',
    username: 'Nom d\'utilisateur',
    avatarUrl: 'URL de l\'avatar',
    platform: 'Plateforme',
    searchPlayer: 'Rechercher joueur...',
    playerNotFound: 'Joueur introuvable',
    backToLobby: 'Retour au lobby',
    wins: 'Victoires',
    losses: 'Défaites',
    winrate: 'Winrate',
    resetStats: 'RAZ Stats',
    resetStatsTitle: 'Réinitialiser vos stats ?',
    resetStatsDesc: 'Cela remettra vos victoires, défaites et points à 0. Votre XP et niveau seront conservés.',
    confirmReset: 'Réinitialiser',
    resetting: 'Réinitialisation...',
    deleteAccount: 'Supprimer le compte',
    deleteAccountTitle: 'Supprimer votre compte ?',
    deleteAccountDesc: 'Cette action est permanente et irréversible. Toutes vos données seront perdues.',
    typeDeleteConfirm: 'Tapez DELETE pour confirmer',
    confirmDelete: 'Supprimer',
    deleting: 'Suppression...',
    
    // Login dialog
    loginTitle: 'Connexion à NoMercy',
    loginSubtitle: 'Connecte-toi avec Discord pour accéder à toutes les fonctionnalités',
    continueWithDiscord: 'Continuer avec Discord',
    termsNotice: 'En te connectant, tu acceptes nos Conditions d\'utilisation',
    
    // Admin
    admin: 'Admin',
    adminPanel: 'Panneau Admin',
    adminPanelDesc: 'Gérer les modes de jeu, les règles et les joueurs',
    gameModes: 'Modes de jeu',
    playerManagement: 'Joueurs',
    searchPlayerPlaceholder: 'Rechercher par pseudo ou ID Activision...',
    statsUpdated: 'Stats mises à jour !',
    saveStats: 'Enregistrer',
    general: 'Général',
    editRules: 'Règles',
    modeEnabled: 'Mode activé et visible pour les joueurs',
    modeDisabled: 'Mode désactivé et masqué pour les joueurs',
    noRulesYet: 'Aucune règle définie',
    addNewRule: 'Ajouter une règle',
    addRule: 'Ajouter',
    done: 'Terminé',
    saved: 'Modifications enregistrées !',
    adminTip: 'Les modifications sont enregistrées automatiquement. Utilisez les interrupteurs pour activer/désactiver les modes.',
    queues: 'Files d\'attente',
    matchmakingQueues: 'Files de matchmaking',
    playersCurrentlyInQueue: 'Joueurs actuellement en file',
    clearAllQueues: 'Vider toutes les files',
    confirmClearQueues: 'Êtes-vous sûr de vouloir retirer tous les joueurs des files d\'attente ?',
    queuesCleared: 'Files vidées',
    queueInfoTip: 'Vider les files retirera tous les joueurs en recherche de match. Ils devront relancer leur recherche.',
    addGameMode: 'Ajouter un mode',
    newGameMode: 'Nouveau mode de jeu',
    editModeName: 'Modifier le nom du mode',
    icon: 'Icône',
    modeType: 'Type de mode',
    addMode: 'Ajouter',
    deleteMode: 'Supprimer le mode',
    rulesDescription: 'Écrivez les règles de ce mode (une règle par ligne)',
    cancel: 'Annuler',
    vipAccess: 'Accorder l\'accès VIP à ce joueur',
  },
  de: {
    // Navbar
    lobby: 'Lobby',
    tournaments: 'Turniere',
    profile: 'Profil',
    login: 'Anmelden',
    logout: 'Abmelden',
    online: 'Online',
    offline: 'Offline',
    
    // Lobby
    chooseYourBattle: 'Wähle deinen Kampf',
    selectGameMode: 'Wähle einen Spielmodus und stürze dich ins Geschehen',
    playNow: 'Jetzt spielen',
    selectMode: 'Modus wählen',
    leaderOnly: 'Nur Leader',
    onlyLeaderCanStart: 'Nur der Gruppenleiter kann ein Match starten',
    notEnoughPlayers: 'Du brauchst {min} Spieler in deiner Gruppe für diesen Modus',
    tooManyPlayers: 'Maximal {max} Spieler erlaubt für diesen Modus',
    pressToFind: 'Drücke um ein Match zu finden in',
    playersOnline: 'Online',
    activeMatches: 'Aktive Matches',
    totalAccounts: 'Konten',
    totalMatches: 'Gespielte Matches',
    totalSquads: 'Squads',
    avgMatchesPerDay: 'Ø/Tag',
    currentGame: 'Aktuelles Spiel',
    serverStatus: 'Server Status',
    optimal: 'Optimal',
    
    // Game modes
    ranked: 'Ranked',
    rankedDesc: 'Wettkampfmatches mit Skill-basiertem Rangsystem',
    casual: 'Casual',
    casualDesc: 'Entspannte Matches zum Spaß ohne Rangdruck',
    tournament: 'Turnier',
    tournamentDesc: 'Offizielle Turnierspiele und Qualifikationen',
    custom: 'Benutzerdefiniert',
    customDesc: 'Erstelle dein eigenes Match mit benutzerdefinierten Regeln',
    playersOnlineCount: 'Spieler online',
    playerOnline: 'Spieler online',
    searching: 'in Suche',
    rules: 'Regeln',
    rulesTitle: 'Spielregeln',
    understood: 'Verstanden',
    
    // Match Search
    searchingMatch: 'Suche nach Match...',
    matchFound: 'Match Gefunden',
    matchInProgress: 'Match Läuft',
    matchFunctionalityComingSoon: 'Match-Funktionen kommen bald',
    minimize: 'Minimieren',
    startingIn: 'Start in',
    connecting: 'Verbindung wird hergestellt...',
    connectingToServer: 'Verbindung zum Server...',
    scanning: 'Scannen',
    joining: 'Beitreten...',
    joiningMatch: 'Match beitreten...',
    searchingDesc: 'Suche nach Spielern in deiner Nähe',
    matchFoundDesc: 'Lobby wird vorbereitet',
    connectingDesc: 'Verbindung zum Match-Server',
    searchTime: 'Suchzeit',
    elapsed: 'Vergangen',
    playersFound: 'Spieler gefunden',
    playersInQueue: 'Spieler in Warteschlange',
    lobbySlots: 'Lobby-Plätze',
    cancelSearch: 'Suche abbrechen',
    doNotClose: 'Bitte dieses Fenster nicht schließen',
    errorJoiningQueue: 'Fehler beim Beitreten der Warteschlange',
    leaderCancelledSearch: 'Der Leader hat die Suche abgebrochen',
    errorOccurred: 'Ein Fehler ist aufgetreten',
    team: 'Team',
    
    // Iris Required
    irisRequired: 'Iris Anti-Cheat Erforderlich',
    irisRequiredDesc: 'Iris muss ausgeführt werden, um nach einem Match zu suchen',
    irisStep1Title: 'Iris herunterladen',
    irisStep1Desc: 'Gehen Sie zur Anti-Cheat-Seite und laden Sie Iris herunter',
    irisStep2Title: 'Installieren & Starten',
    irisStep2Desc: 'Installieren Sie die Anwendung und melden Sie sich mit Discord an',
    irisStep3Title: 'Lassen Sie es laufen',
    irisStep3Desc: 'Iris muss während des Spielens geöffnet bleiben',
    irisInfoText: 'Iris schützt Fair Play, indem es die Integrität Ihres PCs überprüft. Es läuft im Hintergrund mit minimalem Einfluss.',
    downloadIris: 'Iris herunterladen',
    close: 'Schließen',
    
    // Party Panel
    squad: 'Trupp',
    party: 'Gruppe',
    pendingInvites: 'Ausstehende Einladungen',
    groupOf: 's Gruppe',
    members: 'Mitglieder',
    accept: 'Annehmen',
    decline: 'Ablehnen',
    leader: 'Anführer',
    you: 'Du',
    lvl: 'LVL',
    irisConnected: 'Iris Verbunden',
    irisDisconnected: 'Iris Getrennt',
    makeLeader: 'Zum Anführer machen',
    kickFromParty: 'Aus Gruppe entfernen',
    invitePlayer: 'Spieler einladen',
    emptySlot: 'Freier Platz',
    inviteFriends: 'Freunde einladen',
    leaveParty: 'Gruppe verlassen',
    transferToLeave: 'Übertrage die Führung um zu gehen',
    partyPrivacy: 'Gruppeneinstellung',
    inviteOnly: 'Nur auf Einladung',
    
    // Ranked rules
    rankedRule1: 'Matches werden im Best-of-5-Format gespielt',
    rankedRule2: 'Alle Spieler müssen ihr Mikrofon aktiviert haben',
    rankedRule3: 'Cheaten oder Exploiten führt zu einem permanenten Bann',
    rankedRule4: 'Respektiere deine Gegner und Teamkollegen jederzeit',
    
    // Casual rules
    casualRule1: 'Spiele zum Spaß, ohne Druck',
    casualRule2: 'Freundliches Verhalten wird erwartet',
    casualRule3: 'Frühes Verlassen ist erlaubt aber nicht erwünscht',
    
    // Tournament rules
    tournamentRule1: 'Check-in 15 Minuten vor deinem Match',
    tournamentRule2: 'Alle offiziellen Wettkampfregeln gelten',
    tournamentRule3: 'Matchergebnisse sind endgültig',
    tournamentRule4: 'Preise werden innerhalb von 48 Stunden verteilt',
    
    // Custom rules
    customRule1: 'Der Host definiert die Regeln',
    customRule2: 'Stelle sicher dass alle Spieler den Regeln zustimmen',
    customRule3: 'Viel Spaß!',
    
    // Tournaments page
    tournamentsTitle: 'Turniere',
    tournamentsSubtitle: 'Nimm an organisierten Wettkampf-Events teil',
    tournamentComingSoon: 'Das Turniersystem ist in Entwicklung. Bald kannst du an organisierten Wettkampf-Events teilnehmen.',
    tournamentSystemTitle: 'Turniersystem',
    upcoming: 'Kommend',
    ongoing: 'Laufend',
    completed: 'Abgeschlossen',
    date: 'Datum',
    prize: 'Preis',
    players: 'Spieler',
    comingSoon: 'Bald verfügbar',
    backToLobby: 'Zurück zur Lobby',
    
    // Profile page
    profileTitle: 'Profil',
    profileSubtitle: 'Sieh dir deine Statistiken, Erfolge und Einstellungen an',
    profileComingSoon: 'Profil bald verfügbar',
    profileComingSoonDesc: 'Deine Profilseite mit Statistiken, Match-Verlauf und Anpassungsoptionen wird bald verfügbar sein.',
    matches: 'Matches',
    winRate: 'Siegrate',
    rank: 'Rang',
    loading: 'Laden...',
    level: 'Level',
    total: 'gesamt',
    nextLevel: 'Nächstes Level',
    victories: 'Siege',
    defeats: 'Niederlagen',
    coins: 'Münzen',
    editProfile: 'Profil bearbeiten',
    save: 'Speichern',
    saving: 'Speichern...',
    cancel: 'Abbrechen',
    username: 'Benutzername',
    avatarUrl: 'Avatar-URL',
    platform: 'Plattform',
    searchPlayer: 'Spieler suchen...',
    playerNotFound: 'Spieler nicht gefunden',
    backToLobby: 'Zurück zur Lobby',
    wins: 'Siege',
    losses: 'Niederlagen',
    winrate: 'Winrate',
    resetStats: 'Stats zurücksetzen',
    resetStatsTitle: 'Stats zurücksetzen?',
    resetStatsDesc: 'Dies setzt Siege, Niederlagen und Punkte auf 0. XP und Level bleiben erhalten.',
    confirmReset: 'Zurücksetzen',
    resetting: 'Zurücksetzen...',
    deleteAccount: 'Konto löschen',
    deleteAccountTitle: 'Konto löschen?',
    deleteAccountDesc: 'Diese Aktion ist dauerhaft und kann nicht rückgängig gemacht werden.',
    typeDeleteConfirm: 'Gib DELETE ein zur Bestätigung',
    confirmDelete: 'Löschen',
    deleting: 'Löschen...',
    
    // Login dialog
    loginTitle: 'Bei NoMercy anmelden',
    loginSubtitle: 'Verbinde dich mit Discord um alle Funktionen zu nutzen',
    continueWithDiscord: 'Mit Discord fortfahren',
    termsNotice: 'Mit der Anmeldung akzeptierst du unsere Nutzungsbedingungen',
    
    // Admin
    admin: 'Admin',
    adminPanel: 'Admin Panel',
    adminPanelDesc: 'Spielmodi, Regeln und Spieler verwalten',
    gameModes: 'Spielmodi',
    playerManagement: 'Spieler',
    searchPlayerPlaceholder: 'Nach Benutzername oder Activision ID suchen...',
    statsUpdated: 'Stats erfolgreich aktualisiert!',
    saveStats: 'Stats speichern',
    general: 'Allgemein',
    editRules: 'Regeln',
    modeEnabled: 'Modus ist aktiviert und für Spieler sichtbar',
    modeDisabled: 'Modus ist deaktiviert und für Spieler versteckt',
    noRulesYet: 'Noch keine Regeln definiert',
    addNewRule: 'Neue Regel hinzufügen',
    addRule: 'Hinzufügen',
    done: 'Fertig',
    saved: 'Änderungen gespeichert!',
    adminTip: 'Änderungen werden automatisch gespeichert. Schalter zum Aktivieren/Deaktivieren verwenden.',
    queues: 'Warteschlangen',
    matchmakingQueues: 'Matchmaking-Warteschlangen',
    playersCurrentlyInQueue: 'Spieler aktuell in Warteschlange',
    clearAllQueues: 'Alle Warteschlangen leeren',
    confirmClearQueues: 'Möchten Sie wirklich alle Spieler aus den Warteschlangen entfernen?',
    queuesCleared: 'Warteschlangen geleert',
    queueInfoTip: 'Das Leeren der Warteschlangen entfernt alle Spieler, die nach einem Match suchen. Sie müssen erneut suchen.',
    addGameMode: 'Spielmodus hinzufügen',
    newGameMode: 'Neuer Spielmodus',
    editModeName: 'Modusname bearbeiten',
    icon: 'Symbol',
    modeType: 'Modus-Typ',
    addMode: 'Hinzufügen',
    deleteMode: 'Modus löschen',
    rulesDescription: 'Schreiben Sie die Regeln für diesen Modus (eine Regel pro Zeile)',
    cancel: 'Abbrechen',
    vipAccess: 'VIP-Zugang für diesen Spieler gewähren',
  },
  it: {
    // Navbar
    lobby: 'Lobby',
    tournaments: 'Tornei',
    profile: 'Profilo',
    login: 'Accedi',
    logout: 'Esci',
    online: 'Online',
    offline: 'Offline',
    
    // Lobby
    chooseYourBattle: 'Scegli la tua Battaglia',
    selectGameMode: 'Seleziona una modalità di gioco e buttati nell\'azione',
    playNow: 'Gioca Ora',
    selectMode: 'Seleziona Modalità',
    leaderOnly: 'Solo Leader',
    onlyLeaderCanStart: 'Solo il leader del gruppo può avviare una partita',
    notEnoughPlayers: 'Servono {min} giocatore/i nel gruppo per questa modalità',
    tooManyPlayers: 'Massimo {max} giocatore/i per questa modalità',
    pressToFind: 'Premi per trovare una partita in',
    playersOnline: 'Online',
    activeMatches: 'Partite Attive',
    totalAccounts: 'Account',
    totalMatches: 'Partite Giocate',
    totalSquads: 'Squad',
    avgMatchesPerDay: 'Media/Giorno',
    currentGame: 'Gioco Attuale',
    serverStatus: 'Stato Server',
    optimal: 'Ottimale',
    
    // Game modes
    ranked: 'Classificata',
    rankedDesc: 'Partite competitive con sistema di classificazione basato sull\'abilità',
    casual: 'Casual',
    casualDesc: 'Partite rilassate per divertirsi senza pressione',
    tournament: 'Torneo',
    tournamentDesc: 'Partite ufficiali di torneo e qualificazioni',
    custom: 'Personalizzata',
    customDesc: 'Crea la tua partita con regole personalizzate',
    playersOnlineCount: 'giocatori online',
    playerOnline: 'giocatore online',
    searching: 'in ricerca',
    rules: 'Regole',
    rulesTitle: 'Regole del gioco',
    understood: 'Capito',
    
    // Match Search
    searchingMatch: 'Ricerca partita...',
    matchFound: 'Partita Trovata',
    matchInProgress: 'Partita In Corso',
    matchFunctionalityComingSoon: 'Funzionalità partita in arrivo',
    minimize: 'Riduci',
    startingIn: 'Inizia tra',
    connecting: 'Connessione...',
    connectingToServer: 'Connessione al server...',
    scanning: 'Scansione',
    joining: 'Unisciti...',
    joiningMatch: 'Unisciti alla partita...',
    searchingDesc: 'Ricerca giocatori del tuo livello',
    matchFoundDesc: 'Preparazione della lobby',
    connectingDesc: 'Connessione al server di gioco',
    searchTime: 'Tempo di ricerca',
    elapsed: 'Trascorso',
    playersFound: 'Giocatori trovati',
    playersInQueue: 'Giocatori in coda',
    lobbySlots: 'Posti lobby',
    cancelSearch: 'Annulla ricerca',
    doNotClose: 'Non chiudere questa finestra',
    errorJoiningQueue: 'Errore durante l\'accesso alla coda',
    leaderCancelledSearch: 'Il leader ha annullato la ricerca',
    errorOccurred: 'Si è verificato un errore',
    team: 'Squadra',
    
    // Iris Required
    irisRequired: 'Iris Anti-Cheat Richiesto',
    irisRequiredDesc: 'Devi avere Iris in esecuzione per cercare una partita',
    irisStep1Title: 'Scarica Iris',
    irisStep1Desc: 'Vai alla pagina Anti-Cheat e scarica Iris',
    irisStep2Title: 'Installa e Avvia',
    irisStep2Desc: 'Installa l\'applicazione e accedi con Discord',
    irisStep3Title: 'Mantienilo attivo',
    irisStep3Desc: 'Iris deve rimanere aperto mentre giochi',
    irisInfoText: 'Iris protegge il fair play verificando l\'integrità del tuo PC. Funziona in background con impatto minimo.',
    downloadIris: 'Scarica Iris',
    close: 'Chiudi',
    
    // Party Panel
    squad: 'Squadra',
    party: 'Gruppo',
    pendingInvites: 'Inviti in sospeso',
    groupOf: ' del gruppo di',
    members: 'membri',
    accept: 'Accetta',
    decline: 'Rifiuta',
    leader: 'Leader',
    you: 'Tu',
    lvl: 'LIV',
    irisConnected: 'Iris Connesso',
    irisDisconnected: 'Iris Disconnesso',
    makeLeader: 'Rendi Leader',
    kickFromParty: 'Espelli dal gruppo',
    invitePlayer: 'Invita giocatore',
    emptySlot: 'Posto vuoto',
    inviteFriends: 'Invita amici',
    leaveParty: 'Lascia il gruppo',
    transferToLeave: 'Trasferisci la leadership per uscire',
    partyPrivacy: 'Privacy gruppo',
    inviteOnly: 'Solo su invito',
    
    // Ranked rules
    rankedRule1: 'Le partite si giocano in formato Best of 5',
    rankedRule2: 'Tutti i giocatori devono avere il microfono attivato',
    rankedRule3: 'Barare o sfruttare bug comporterà un ban permanente',
    rankedRule4: 'Rispetta i tuoi avversari e compagni di squadra sempre',
    
    // Casual rules
    casualRule1: 'Gioca per divertirti, senza pressione',
    casualRule2: 'È previsto un comportamento amichevole',
    casualRule3: 'Uscire presto è permesso ma non incoraggiato',
    
    // Tournament rules
    tournamentRule1: 'Check-in 15 minuti prima della partita',
    tournamentRule2: 'Si applicano tutte le regole competitive ufficiali',
    tournamentRule3: 'I risultati delle partite sono definitivi',
    tournamentRule4: 'I premi saranno distribuiti entro 48 ore',
    
    // Custom rules
    customRule1: 'L\'host definisce le regole',
    customRule2: 'Assicurati che tutti i giocatori accettino le regole',
    customRule3: 'Divertiti!',
    
    // Tournaments page
    tournamentsTitle: 'Tornei',
    tournamentsSubtitle: 'Partecipa a eventi competitivi organizzati',
    tournamentComingSoon: 'Il sistema tornei è in sviluppo. Presto potrai partecipare a eventi competitivi organizzati.',
    tournamentSystemTitle: 'Sistema Tornei',
    upcoming: 'In arrivo',
    ongoing: 'In corso',
    completed: 'Completato',
    date: 'Data',
    prize: 'Premio',
    players: 'Giocatori',
    comingSoon: 'Prossimamente',
    backToLobby: 'Torna alla Lobby',
    
    // Profile page
    profileTitle: 'Profilo',
    profileSubtitle: 'Visualizza le tue statistiche, successi e impostazioni',
    profileComingSoon: 'Profilo in arrivo',
    profileComingSoonDesc: 'La tua pagina profilo con statistiche, cronologia partite e opzioni di personalizzazione sarà presto disponibile.',
    matches: 'Partite',
    winRate: 'Winrate',
    rank: 'Rango',
    loading: 'Caricamento...',
    level: 'Livello',
    total: 'totale',
    nextLevel: 'Prossimo livello',
    victories: 'Vittorie',
    defeats: 'Sconfitte',
    coins: 'Monete',
    editProfile: 'Modifica profilo',
    save: 'Salva',
    saving: 'Salvataggio...',
    cancel: 'Annulla',
    username: 'Nome utente',
    avatarUrl: 'URL avatar',
    platform: 'Piattaforma',
    searchPlayer: 'Cerca giocatore...',
    playerNotFound: 'Giocatore non trovato',
    backToLobby: 'Torna alla lobby',
    wins: 'Vittorie',
    losses: 'Sconfitte',
    winrate: 'Winrate',
    resetStats: 'Reset Stats',
    resetStatsTitle: 'Resettare le stats?',
    resetStatsDesc: 'Questo resetterà vittorie, sconfitte e punti a 0. XP e livello saranno mantenuti.',
    confirmReset: 'Resetta',
    resetting: 'Resettando...',
    deleteAccount: 'Elimina Account',
    deleteAccountTitle: 'Eliminare l\'account?',
    deleteAccountDesc: 'Questa azione è permanente e non può essere annullata. Tutti i dati andranno persi.',
    typeDeleteConfirm: 'Digita DELETE per confermare',
    confirmDelete: 'Elimina',
    deleting: 'Eliminazione...',
    
    // Login dialog
    loginTitle: 'Accedi a NoMercy',
    loginSubtitle: 'Connettiti con Discord per accedere a tutte le funzionalità',
    continueWithDiscord: 'Continua con Discord',
    termsNotice: 'Accedendo, accetti i nostri Termini di Servizio',
    
    // Admin
    admin: 'Admin',
    adminPanel: 'Pannello Admin',
    adminPanelDesc: 'Gestisci modalità di gioco, regole e giocatori',
    gameModes: 'Modalità di gioco',
    playerManagement: 'Giocatori',
    searchPlayerPlaceholder: 'Cerca per nome utente o ID Activision...',
    statsUpdated: 'Stats aggiornate con successo!',
    saveStats: 'Salva Stats',
    general: 'Generale',
    editRules: 'Regole',
    modeEnabled: 'Modalità attivata e visibile ai giocatori',
    modeDisabled: 'Modalità disattivata e nascosta ai giocatori',
    noRulesYet: 'Nessuna regola definita',
    addNewRule: 'Aggiungi nuova regola',
    addRule: 'Aggiungi',
    done: 'Fatto',
    saved: 'Modifiche salvate!',
    adminTip: 'Le modifiche vengono salvate automaticamente. Usa gli interruttori per attivare/disattivare le modalità.',
    queues: 'Code',
    matchmakingQueues: 'Code di matchmaking',
    playersCurrentlyInQueue: 'Giocatori attualmente in coda',
    clearAllQueues: 'Svuota tutte le code',
    confirmClearQueues: 'Sei sicuro di voler rimuovere tutti i giocatori dalle code?',
    queuesCleared: 'Code svuotate',
    queueInfoTip: 'Svuotare le code rimuoverà tutti i giocatori in cerca di una partita. Dovranno cercare di nuovo.',
    addGameMode: 'Aggiungi modalità',
    newGameMode: 'Nuova modalità di gioco',
    editModeName: 'Modifica nome modalità',
    icon: 'Icona',
    modeType: 'Tipo di modalità',
    addMode: 'Aggiungi',
    deleteMode: 'Elimina modalità',
    rulesDescription: 'Scrivi le regole per questa modalità (una regola per riga)',
    cancel: 'Annulla',
    vipAccess: 'Concedi accesso VIP a questo giocatore',
  }
}

const LanguageContext = createContext(null)

export const LanguageProvider = ({ children }) => {
  // Load saved language from localStorage, default to French
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('nomercy-language')
    return saved || 'fr'
  })

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('nomercy-language', language)
  }, [language])

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key
  }

  const changeLanguage = (lang) => {
    setLanguage(lang)
  }

  const availableLanguages = [
    { code: 'fr', label: 'FR', flag: '/flags/fr.png' },
    { code: 'en', label: 'EN', flag: '/flags/gb.png' },
    { code: 'de', label: 'DE', flag: '/flags/de.png' },
    { code: 'it', label: 'IT', flag: '/flags/it.png' },
  ]

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage, availableLanguages }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
